import React, { useState, useEffect } from 'react';
import { UserProfile } from '../../types';
import { getCareerSuggestions } from '../../services/geminiService';
import { Sparkles, Zap, Target, Lightbulb, RefreshCw, ChevronRight, BrainCircuit, Rocket } from 'lucide-react';

interface CareerIntelViewProps {
  user: UserProfile;
}

const CareerIntelView: React.FC<CareerIntelViewProps> = ({ user }) => {
  const [suggestions, setSuggestions] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchSuggestions = async () => {
    setLoading(true);
    const data = await getCareerSuggestions(user.role, user.location);
    setSuggestions(data);
    setLoading(false);
  };

  useEffect(() => {
    fetchSuggestions();
  }, [user.role, user.location]);

  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 pb-20">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight mb-2 flex items-center gap-3">
            AI Career Intelligence <Sparkles className="w-6 h-6 text-amber-500 fill-amber-500" />
          </h1>
          <p className="text-slate-500 dark:text-slate-400">Personalized strategic roadmap generated by Gemini for your specific role and market</p>
        </div>
        
        <button 
          onClick={fetchSuggestions}
          disabled={loading}
          className="flex items-center gap-2 bg-indigo-50 dark:bg-indigo-950/30 text-indigo-600 dark:text-indigo-400 px-6 py-3 rounded-2xl font-bold hover:bg-indigo-100 dark:hover:bg-indigo-900/50 transition-all border border-indigo-100 dark:border-indigo-900/50 disabled:opacity-50"
        >
          <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          Refresh Insights
        </button>
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center min-h-[400px] text-center">
          <div className="relative mb-8">
            <div className="w-24 h-24 rounded-full border-4 border-indigo-500/20 border-t-indigo-500 animate-spin"></div>
            <BrainCircuit className="w-10 h-10 text-indigo-500 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
          </div>
          <h3 className="text-xl font-bold mb-2">Analyzing the Market...</h3>
          <p className="text-slate-500 dark:text-slate-400 max-w-xs mx-auto italic">Gemini is connecting current trends with your profile to build your strategic advantage.</p>
        </div>
      ) : (
        <div className="space-y-12">
          {/* Top Insights Row */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {suggestions.map((item, idx) => (
              <div 
                key={idx}
                className="bg-white dark:bg-[#111] rounded-[2.5rem] p-8 border border-slate-200 dark:border-slate-800 relative overflow-hidden group hover:border-indigo-500/50 transition-all duration-500 shadow-sm"
              >
                <div className="absolute top-0 right-0 p-8 opacity-[0.03] group-hover:opacity-[0.08] transition-opacity">
                  <Target className="w-32 h-32" />
                </div>
                
                <div className="flex items-center gap-3 mb-6">
                  <div className="p-3 rounded-2xl bg-indigo-50 dark:bg-indigo-950/30 text-indigo-600 dark:text-indigo-400">
                    <Lightbulb className="w-5 h-5" />
                  </div>
                  <span className="text-[10px] font-extrabold uppercase tracking-widest text-slate-400">{item.category}</span>
                </div>

                <h3 className="text-xl font-extrabold mb-4 text-slate-900 dark:text-white group-hover:text-indigo-600 transition-colors">
                  {item.title}
                </h3>
                <p className="text-slate-500 dark:text-slate-400 leading-relaxed mb-8">
                  {item.description}
                </p>

                <button className="flex items-center gap-2 text-indigo-600 font-bold text-sm group-hover:gap-3 transition-all">
                  Explore Implementation <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>

          {/* Strategic Pillar */}
          <div className="bg-gradient-to-r from-slate-900 to-indigo-950 rounded-[3rem] p-8 md:p-12 text-white relative overflow-hidden">
            <div className="relative z-10 grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              <div>
                <div className="flex items-center gap-3 mb-6">
                  <div className="bg-white/10 p-2 rounded-xl backdrop-blur-md">
                    <Rocket className="w-5 h-5 text-indigo-300" />
                  </div>
                  <h2 className="text-2xl font-bold">Strategic Pivot Pillar</h2>
                </div>
                <p className="text-indigo-100/70 text-lg mb-8 leading-relaxed">
                  Based on your current role as a {user.role}, the primary "Market Alpha" skill gap in {user.location} is <span className="text-white font-bold underline decoration-indigo-500 underline-offset-4">Strategic Product Thinking with AI Implementation</span>.
                </p>
                <div className="flex flex-wrap gap-3">
                  {['AI Workflow Optimization', 'Systems Thinking', 'Data-Driven Design'].map(tag => (
                    <span key={tag} className="px-4 py-2 bg-white/5 border border-white/10 rounded-xl text-xs font-bold uppercase tracking-wider">{tag}</span>
                  ))}
                </div>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="bg-white/5 backdrop-blur-md p-6 rounded-3xl border border-white/10">
                  <p className="text-indigo-300 text-[10px] font-extrabold uppercase mb-2">Market Velocity</p>
                  <p className="text-2xl font-bold">+24% YoY</p>
                </div>
                <div className="bg-white/5 backdrop-blur-md p-6 rounded-3xl border border-white/10">
                  <p className="text-indigo-300 text-[10px] font-extrabold uppercase mb-2">Resiliency Score</p>
                  <p className="text-2xl font-bold">8.4 / 10</p>
                </div>
                <div className="bg-white/5 backdrop-blur-md p-6 rounded-3xl border border-white/10 col-span-2">
                  <p className="text-indigo-300 text-[10px] font-extrabold uppercase mb-2">Priority Path</p>
                  <p className="text-lg font-bold">Senior Platform Product Designer</p>
                </div>
              </div>
            </div>
            {/* Decorative background circle */}
            <div className="absolute top-0 right-0 w-96 h-96 bg-indigo-600/10 rounded-full blur-[100px] -mr-48 -mt-48"></div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CareerIntelView;
