
// Your custom tech roles
export const techRolesRaw = [
  "AI Engineer",
  "AI Researcher",
  "AR/VR Developer",
  "Automation Engineer",
  "Back End Developer",
  "Backend Engineer",
  "Blockchain Developer",
  "Cloud Engineer",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Database Administrator",
  "DevOps Engineer",
  "Embedded Systems Engineer",
  "Engineering Manager",
  "Frontend Engineer",
  "Full Stack Developer",
  "Game Developer",
  "IT Project Manager",
  "IT Support Specialist",
  "Integration Engineer",
  "Machine Learning Engineer",
  "Marketing Lead",
  "Mobile Developer",
  "Network Engineer",
  "Platform Engineer",
  "Product Designer",
  "Product Engineer",
  "Product Manager",
  "Principal Engineer",
  "QA / Test Engineer",
  "Release Manager",
  "Security Engineer",
  "Site Reliability Engineer",
  "Solutions Architect",
  "Software Developer",
  "Software Engineer",
  "Staff Engineer",
  "Systems Administrator",
  "Systems Architect",
  "Tech Lead",
  "Technical Program Manager",
  "UX Researcher",
  "UX/UI Engineer"
];

export const PRIORITY_CITIES = [
  'Toronto, ON',
  'Ottawa, ON',
  'New York, NY',
  'Los Angeles, CA',
  'San Francisco, CA',
  'Washington, DC',
];
