import type { ClarityState, DemoStateKey } from '../types';

export const ROLE_OPTIONS = [
  'Account Manager',
  'Administrative Assistant',
  'AI Product Manager',
  'Business Analyst',
  'Business Development Manager',
  'Chief of Staff',
  'Compliance Analyst',
  'Content Strategist',
  'Customer Experience Manager',
  'Customer Success Manager',
  'Cybersecurity Analyst',
  'Data Analyst',
  'Data Engineer',
  'Data Scientist',
  'Digital Marketing Manager',
  'Engineering Manager',
  'Finance Manager',
  'Financial Analyst',
  'Frontend Developer',
  'Full Stack Developer',
  'Graphic Designer',
  'HR Business Partner',
  'Implementation Manager',
  'Information Security Manager',
  'IT Project Manager',
  'Management Consultant',
  'Marketing Manager',
  'Operations Analyst',
  'Operations Manager',
  'Product Designer',
  'Product Manager',
  'Product Marketing Manager',
  'Product Operations Manager',
  'Program Manager',
  'Project Coordinator',
  'Project Manager',
  'Quality Assurance Analyst',
  'Risk Analyst',
  'Sales Manager',
  'Scrum Master',
  'Software Engineer',
  'Solutions Architect',
  'Solutions Consultant',
  'Supply Chain Analyst',
  'Talent Acquisition Manager',
  'Technical Product Manager',
  'Technical Program Manager',
  'UX Designer',
  'UX Researcher',
] as const;

export const INDUSTRY_OPTIONS = [
  'Accounting',
  'Advertising and Marketing',
  'Agriculture',
  'Automotive',
  'Banking',
  'Biotechnology',
  'Construction',
  'Consulting',
  'Consumer Goods',
  'Cybersecurity',
  'Education',
  'Energy and Utilities',
  'Engineering',
  'Entertainment and Media',
  'Financial Services',
  'Fintech',
  'Government and Public Sector',
  'Healthcare',
  'Hospitality and Tourism',
  'Human Resources',
  'Insurance',
  'Legal Services',
  'Logistics and Supply Chain',
  'Manufacturing',
  'Nonprofit',
  'Pharmaceuticals',
  'Professional Services',
  'Real Estate',
  'Retail and E-commerce',
  'Software and SaaS',
  'Telecommunications',
  'Transportation',
  'Technology',
] as const;

export const LOCATION_OPTIONS = [
  'Toronto, Ontario, Canada',
  'Vancouver, British Columbia, Canada',
  'Montreal, Quebec, Canada',
  'Calgary, Alberta, Canada',
  'Ottawa, Ontario, Canada',
  'Edmonton, Alberta, Canada',
  'Winnipeg, Manitoba, Canada',
  'Halifax, Nova Scotia, Canada',
  'Mississauga, Ontario, Canada',
  'Brampton, Ontario, Canada',
  'Hamilton, Ontario, Canada',
  'Kitchener-Waterloo, Ontario, Canada',
  'London, Ontario, Canada',
  'Sudbury, Ontario, Canada',
  'New York, New York, USA',
  'San Francisco Bay Area, California, USA',
  'Los Angeles, California, USA',
  'Chicago, Illinois, USA',
  'Boston, Massachusetts, USA',
  'Seattle, Washington, USA',
  'Austin, Texas, USA',
  'Dallas–Fort Worth, Texas, USA',
  'Atlanta, Georgia, USA',
  'Washington, DC, USA',
  'Miami, Florida, USA',
  'London, United Kingdom',
  'Manchester, United Kingdom',
  'Dublin, Ireland',
  'Lagos, Nigeria',
  'Abuja, Nigeria',
  'Nairobi, Kenya',
  'Johannesburg, South Africa',
  'Dubai, United Arab Emirates',
  'Remote — Canada',
  'Remote — United States',
  'Remote — Global',
] as const;

export const SKILL_OPTIONS = [
  'Account Management',
  'Agile Delivery',
  'AI Literacy',
  'API Design',
  'API Products',
  'Business Analysis',
  'Business Case Development',
  'Business Development',
  'Change Management',
  'Cloud Computing',
  'Coaching and Mentoring',
  'Commercial Strategy',
  'Communication',
  'Compliance',
  'Content Strategy',
  'Contract Negotiation',
  'Cross-functional Leadership',
  'Customer Experience',
  'Customer Research',
  'Customer Success',
  'Cybersecurity',
  'Data Analysis',
  'Data Governance',
  'Data Literacy',
  'Data Visualization',
  'Design Thinking',
  'Digital Marketing',
  'Digital Transformation',
  'Enterprise Sales',
  'Facilitation',
  'Financial Analysis',
  'Financial Modelling',
  'Fraud Prevention',
  'Go-to-Market Strategy',
  'Human Resources',
  'Implementation Management',
  'Information Security',
  'Innovation Strategy',
  'Leadership',
  'Machine Learning',
  'Market Research',
  'Marketing Analytics',
  'Negotiation',
  'Operations Management',
  'Organizational Design',
  'Payments',
  'People Management',
  'Portfolio Management',
  'Presentation Skills',
  'Process Improvement',
  'Product Analytics',
  'Product Discovery',
  'Product Management',
  'Product Marketing',
  'Product Operations',
  'Product Strategy',
  'Program Management',
  'Project Management',
  'Quality Assurance',
  'Regulatory Compliance',
  'Relationship Management',
  'Requirements Gathering',
  'Risk Management',
  'Roadmap Planning',
  'Sales Strategy',
  'Scrum',
  'Service Design',
  'Software Development',
  'Solution Consulting',
  'SQL',
  'Stakeholder Management',
  'Strategic Planning',
  'Supply Chain Management',
  'Systems Analysis',
  'Talent Acquisition',
  'Team Management',
  'Technical Writing',
  'User Research',
  'UX Design',
  'Vendor Management',
] as const;

export const INITIAL_STATE: ClarityState = {
  tool: 'pivot',
  jobSource: 'paste',
  challenge: 'career-change',
  job: {
    title: 'Senior Product Manager',
    company: 'Northstar Financial',
    location: 'Toronto, Canada',
  },
  jobPostingText:
    'Senior Product Manager — Northstar Financial\n\nOwn product strategy and roadmap, lead cross-functional delivery, use customer and performance data to improve measurable outcomes, and influence senior stakeholders across the organization.',
  jobUrl: '',
  jobUploadFileName: null,
  jobLiveAnalysis: null,
  jobLiveError: null,
  jobHasAnalyses: false,
  pivot: {
    title: 'Product Manager',
    industry: 'Financial Services',
    experience: 'Senior',
    location: 'Toronto, Canada',
    goal: 'Better job security',
    skills: ['Product strategy', 'Payments', 'Customer research', 'Analytics'],
  },
  market: {
    role: 'Product Manager',
    industry: 'Financial Services',
    location: 'Toronto, Canada',
    level: 'Senior',
    workPreference: 'Any',
  },
  registered: false,
  profileModal: false,
  profilePageStep: 0,
  profileOrigin: 'profile',
  profileSource: 'linkedin',
  profileComplete: false,
  manualEditor: false,
  manualExperienceSaved: false,
  entryPoint: 'landing',
  workState: 'none',
  pendingGuest: null,
  accountMenuOpen: false,
  signoutConfirm: false,
  theme: 'system',
  demoPanelOpen: false,
  toastMessage: null,
  postAuthRoute: null,
  marketHasReports: false,
  marketGuestReady: false,
  marketGuestSaved: false,
  marketCreateMode: false,
  marketSnapshotDate: null,
  marketReportTab: 'overview',
  marketOpportunityView: 'roles',
  marketOpportunityDetail: null,
  marketLiveInsights: null,
  marketLiveError: null,
  marketGenerationStatus: 'idle',
  marketSnapshotId: null,
};

export const DEMO_STATES: Array<[DemoStateKey, string]> = [
  ['landing', 'Landing page'],
  ['signup', 'Direct account creation'],
  ['new', 'New-account Home'],
  ['none', 'Returning · no saved work'],
  ['unfinished', 'Returning · unfinished work'],
  ['complete', 'Returning · completed work'],
  ['guest-pivot', 'Guest Career Pivot'],
  ['saved-pivot', 'Saved guest Pivot result'],
  ['pivot-profile', 'Profile from Career Pivot'],
  ['guest-job', 'Guest Job Analyzer'],
  ['saved-job', 'Saved guest Job result'],
  ['guest-market', 'Guest Market Report'],
  ['saved-market', 'Saved guest Market result'],
  ['profile', 'Career Profile from Home'],
  ['skills-gated', 'Skills Match · profile needed'],
  ['skills-ready', 'Skills Match · profile ready'],
  ['job-empty', 'Job Analyzer · empty'],
  ['job-history', 'Job Analyzer · history'],
  ['job-new', 'Job Analyzer · new'],
  ['job-review', 'Job Analyzer · review'],
  ['job-result', 'Job Analyzer · result'],
  ['market-empty', 'Market Report · no profile'],
  ['market-profile', 'Market Report · profile prefilled'],
  ['market-generating', 'Market Report · generating'],
  ['market-result', 'Market Report · overview'],
  ['market-insights', 'Market Report · all insights'],
  ['market-full', 'Market Report · full report'],
  ['market-history', 'Market Report · previous reports'],
];

/** Index of the first Market Report entry in {@link DEMO_STATES}. */
export const DEMO_MARKET_START = DEMO_STATES.findIndex(([key]) => key === 'market-empty');

export const icon = (name: string): string =>
  (
    {
      job: '⌕',
      pivot: '↗',
      market: '⌁',
      home: '⌂',
      profile: '◎',
      skills: '≋',
      plan: '✓',
    } as Record<string, string>
  )[name] || '•';

export const selectOptions = (items: readonly string[], current: string): string[] => [
  current,
  ...items.filter((x) => x !== current),
];
